ansible_connection: winrm
ansible_port: 5986
ansible_winrm_transport: basic
ansible_winrm_scheme: https
ansible_winrm_server_cert_validation: ignore
ansible_user: Administrator
# ansible_password: "{{ lookup('aws_ssm', '/path/to/win/admin/password') }}"  # or store securely

